src/BlogBundle/Entity/Transaction.php
<?php
/**
 * Created by PhpStorm.
 * User: rail
 * Date: 09.12.16
 * Time: 15:34
 */

namespace BlogBundle\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints\DateTime;
use Symfony\Component\Validator\Constraints as Assert;
use DateTime as DT;
/**
 * @ORM\Entity(repositoryClass="BlogBundle\Entity\Repository\TransactionRepository")
 * @ORM\Table(name="transaction")
 */
class Transaction
{


    /**
     * @ORM\Id
     * @ORM\Column(type="integer")
     * @ORM\GeneratedValue(strategy="SEQUENCE")
     */
    protected $id;


    /**
     * @ORM\Column(type="float")
     * @Assert\NotNull()
     * @Assert\GreaterThan(
     *     value = 0
     * )
     *  * @Assert\LessThanOrEqual(
     *     value = 1000
     * )
     */
    protected $amount;


    /**
     * @ORM\ManyToOne(targetEntity="User",cascade="persist",fetch="EAGER",inversedBy="outTransactions")
     */
    protected $sourceUser;

    /**
     * @ORM\ManyToOne(targetEntity="User",cascade="persist",fetch="EAGER",inversedBy="inTransactions")
     */
    protected $targetUser;

    /**
     * @ORM\Column(type="boolean")
     */
    protected $is_payment;

    /**
     * @ORM\Column(type="datetime")
     */
    protected $datetime;

    /**
     * Transaction constructor.
     * @param $id
     * @param $amount
     * @param $sourceUser
     * @param $targetUser
     * @param $is_payment
     */
    public function __construct()
    {
        $this->sourceUser = new ArrayCollection();
        $this->targetUser = new ArrayCollection();
        $this->is_payment = false;
        $this->setDatetime(new DT());
    }

    /**
     * @return mixed
     */
    public function getDatetime()
    {
        return $this->datetime;
    }

    /**
     * @param mixed $datetime
     */
    public function setDatetime($datetime)
    {
        $this->datetime = $datetime;
    }


    /**
     * @return mixed
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * @param mixed $id
     */
    public function setId($id)
    {
        $this->id = $id;
    }

    /**
     * @return mixed
     */
    public function getAmount()
    {
        return $this->amount;
    }

    /**
     * @param mixed $amount
     */
    public function setAmount($amount)
    {
        $this->amount = $amount;
    }

    /**
     * @return mixed
     */
    public function getSourceUser()
    {
        return $this->sourceUser;
    }

    /**
     * @param mixed $sourceUser
     */
    public function setSourceUser($sourceUser)
    {
        $this->sourceUser = $sourceUser;
    }

    /**
     * @return mixed
     */
    public function getTargetUser()
    {
        return $this->targetUser;
    }

    /**
     * @param mixed $targetUser
     */
    public function setTargetUser($targetUser)
    {
        $this->targetUser = $targetUser;
    }

    /**
     * @return mixed
     */
    public function getIsPayment()
    {
        return $this->is_payment;
    }

    /**
     * @param mixed $is_payment
     */
    public function setIsPayment($is_payment)
    {
        $this->is_payment = $is_payment;
    }


}

src/BlogBundle/Controller/PaymentController.php
<?php
/**
 * Created by PhpStorm.
 * User: rail
 * Date: 30.11.16
 * Time: 21:36
 */

namespace BlogBundle\Controller;


use BlogBundle\Entity\AsyncTask;
use BlogBundle\Entity\Post;
use BlogBundle\Entity\Repository\AsyncTaskRepository;
use BlogBundle\Entity\Repository\PostRepository;
use BlogBundle\Entity\Repository\TransactionRepository;
use BlogBundle\Entity\Transaction;
use BlogBundle\Entity\User;
use BlogBundle\Form\PayForm;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\Form\Extension\Core\Type\NumberType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\HttpFoundation\Request;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use Symfony\Component\VarDumper\VarDumper;

class PaymentController extends Controller
{
    /**
     * @Route("/buy_post", name="buy_post")
     */
    public function actionBuyPost(Request $request)
    {
        $em = $this->getDoctrine()->getManager();
        /** @var User $user */
        $user = $this->getUser();
        $post_id = $_GET['post_id'];
        $price = 100;
        /** @var  $post_repository PostRepository */
        $post_repository = $em->getRepository('BlogBundle:Post');
        /** @var Post $post */
        $post = $post_repository->find($post_id);
        if (!$post->getIsFree()) {
            if ($user->getBalance() >= $price) {
                $is_yet_buy = false;
                /** @var Post $buy_post */
                foreach ($user->getUserAssignPosts() as $buy_post) {
                    if ($post->getId() == $buy_post->getId()) {
                        $is_yet_buy = true;
                    }
                }
                if (!$is_yet_buy) {
                    $task = new AsyncTask();
                    $task->setContent(json_encode(['source_user_id' => $user->getId(), 'post_id' => $post_id]));
                    /** @var AsyncTaskRepository $task_repository */
                    $task_repository = $em->getRepository('BlogBundle:AsyncTask');
                    $task_repository->saveBuyPostAsyncTask($task);
                } else {
                    $this->get('session')->setFlash(
                        'notice',
                        'Вы уже покупали этот пост!'
                    );
                }
            } else {
                $this->get('session')->setFlash(
                    'notice',
                    'Недостаточно денег пополните кошелек'
                );
            }
        } else {
            $this->get('session')->setFlash(
                'notice',
                'Пост бесплатный его не нужно покупать'
            );
        }
        return $this->redirect($this->generateUrl('post', ['post_id' => $post_id]));
    }

    /**
     * @Route("/pay", name="pay")
     */
    public function actionPay(Request $request)
    {
        $em = $this->getDoctrine()->getManager();
        /** @var TransactionRepository $transaction_repository */
        $transaction_repository = $em->getRepository('BlogBundle:Transaction');
        $user = $this->getUser();
        $transactions = $transaction_repository->getTransactionByUser($user);
        $transaction = new Transaction();
        $transaction->setIsPayment(true);
        $transaction->setSourceUser($user);
        $transaction->setTargetUser($user);
        $form = $this->createForm(PayForm::class, $transaction);
        $form->handleRequest($request);
        if ($form->isValid()) {
            $task = new AsyncTask();
            $content = json_encode(['user_id' => $user->getId(), 'amount' => $transaction->getAmount()]);
            $task->setContent($content);
            /** @var AsyncTaskRepository $task_repository */
            $task_repository = $em->getRepository('BlogBundle:AsyncTask');
            $task_repository->saveDepositAsyncTask($task);
            $transaction_repository->save($transaction);
            return $this->redirect($this->generateUrl('transactions'));
        }

        return $this->render('BlogBundle:Payment:index.html.twig', ['form' => $form->createView(), 'transactions' => $transactions]);
    }

    /**
     * @Route("/trandactions", name="transactions")
     */
    public function actionTransactions(Request $request)
    {
        $em = $this->getDoctrine()->getManager();
        /** @var TransactionRepository $transaction_repository */
        $transaction_repository = $em->getRepository('BlogBundle:Transaction');
        $user = $this->getUser();
        $transactions = $transaction_repository->getTransactionByUser($user);

        return $this->render('BlogBundle:Payment:transactions.html.twig', ['transactions' => $transactions]);
    }
}

src/BlogBundle/Resources/views/Payment/index.html.twig
{# src/Blogger/BlogBundle/Resources/views/Page/index.html.twig #}
{% extends 'BlogBundle::layout.html.twig' %}

{% block body %}

    {{ form_start(form, { 'action': path('pay') , 'method': 'POST', 'attr': {'class': 'blogger'} }) }}

    {{ form_widget(form) }}
    {{ form_end(form) }}


    <table class="table">
        <tr>
            <th>От кого</th>
            <th>Кому</th>
            <th>Сумма</th>
            <th>Время</th>
        </tr>
        {% for transaction in transactions %}
            <tr>
                <td> {% if transaction.isPayment %}
                        Платежка
                    {% else %}
                        {{ transaction.sourceUser.username }}
                    {% endif %}
                </td>
                <td>{{ transaction.targetUser.username }}</td>
                <td>{{ transaction.amount }}</td>
                <td>
                   {{ transaction.datetime|date("h:m:s m-d-Y") }}
                </td>
            </tr>
        {% else %}
            <p>Платежей нет</p>
        {% endfor %}
    </table>
{% endblock %}

src/BlogBundle/Resources/views/Payment/transactions.html.twig
{# src/Blogger/BlogBundle/Resources/views/Page/index.html.twig #}
{% extends 'BlogBundle::layout.html.twig' %}

{% block body %}
    <table class="table">
        <tr>
            <th>От кого</th>
            <th>Кому</th>
            <th>Сумма</th>
            <th>Время</th>
        </tr>
        {% for transaction in transactions %}
            <tr>
                <td> {% if transaction.isPayment %}
                        Платежка
                    {% else %}
                        {{ transaction.sourceUser.username }}
                    {% endif %}
                </td>
                <td>{{ transaction.targetUser.username }}</td>
                <td>{{ transaction.amount }}</td>
                <td>
                    {{ transaction.datetime|date("h:m:s m-d-Y") }}
                </td>
            </tr>
        {% else %}
            <p>Платежей нет</p>
        {% endfor %}
    </table>
{% endblock %}