src/BlogBundle/Entity/Post.php
<?php
namespace BlogBundle\Entity;

use DateTime;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="BlogBundle\Entity\Repository\PostRepository")
 * @ORM\Table(name="post")
 */
class Post
{
    /**
     * @ORM\Id
     * @ORM\Column(type="integer")
     * @ORM\GeneratedValue(strategy="SEQUENCE")
     */
    protected $id;

    /**
     * @ORM\Column(type="string",nullable=false)
     */
    protected $title;

    /**
     * @ORM\Column(type="string",nullable=false)
     */
    protected $body;

    /**
     * @ORM\Column(type="boolean")
     */
    protected $is_free = true;

    /**
     * @ORM\ManyToOne(targetEntity="User",cascade="persist",fetch="EAGER",inversedBy="posts")
     */
    protected $user;


    /**
     * One Product has Many Features.
     * @ORM\OneToMany(targetEntity="Like", mappedBy="post",fetch="EAGER")
     */
    protected $likes;


    /**
     * @ORM\ManyToMany(targetEntity="Teg")
     * @ORM\JoinTable(name="post_tegs",
     *     joinColumns={@ORM\JoinColumn(name="post_id", referencedColumnName="id")},
     *     inverseJoinColumns={@ORM\JoinColumn(name="teg_id", referencedColumnName="id")}
     * )
     *
     * @var ArrayCollection $posts
     */
    protected $tegs;


    /**
     * @return Like[]
     */
    public function getLikes()
    {
        return $this->likes;
    }

    /**
     * @param ArrayCollection $likes
     */
    public function setLikes($likes)
    {
        $this->likes = $likes;
    }

    /**
     * @return mixed
     */
    public function getUser()
    {
        return $this->user;
    }

    /**
     * @ORM\Column(type="datetime")
     */
    protected $created_at;

    /**
     * @ORM\Column(type="datetime")
     */
    protected $updated_at;

    public function __construct()
    {
        $this->setLikes(new ArrayCollection());
        $this->setTegs(new ArrayCollection());
        $this->setCreatedAt(new DateTime());
        $this->setUpdatedAt(new DateTime());
    }

    /**
     * Get id
     *
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set title
     *
     * @param string $title
     *
     * @return Post
     */
    public function setTitle($title)
    {
        $this->title = $title;

        return $this;
    }


    /**
     * Get title
     *
     * @return string
     */
    public function getTitle()
    {
        return $this->title;
    }

    /**
     * Set body
     *
     * @param string $body
     *
     * @return Post
     */
    public function setBody($body)
    {
        $this->body = $body;

        return $this;
    }

    /**
     * Get body
     *
     * @return string
     */
    public function getBody()
    {
        return $this->body;
    }

    /**
     * Set createdAt
     *
     * @param \DateTime $createdAt
     *
     * @return Post
     */
    public function setCreatedAt($createdAt)
    {
        $this->created_at = $createdAt;

        return $this;
    }

    /**
     * Get createdAt
     *
     * @return \DateTime
     */
    public function getCreatedAt()
    {
        return $this->created_at;
    }

    /**
     * Set updatedAt
     *
     * @param \DateTime $updatedAt
     *
     * @return Post
     */
    public function setUpdatedAt($updatedAt)
    {
        $this->updated_at = $updatedAt;

        return $this;
    }

    /**
     * Get updatedAt
     *
     * @return \DateTime
     */
    public function getUpdatedAt()
    {
        return $this->updated_at;
    }

    /**
     * Set profile
     *
     * @param User $user
     *
     * @return Post
     */
    public function setUser(User $user = null)
    {
        $this->user = $user;

        return $this;
    }

    /**
     * Get profile
     *
     * @return User
     */
    public function getProfile()
    {
        return $this->user;
    }

    /**
     * @return ArrayCollection
     */
    public function getTegs()
    {
        return $this->tegs;
    }

    /**
     * @param ArrayCollection $tegs
     */
    public function setTegs($tegs)
    {
        $this->tegs = $tegs;
    }

    /**
     * @return mixed
     */
    public function getIsFree()
    {
        return $this->is_free;
    }

    /**
     * @param mixed $is_free
     */
    public function setIsFree($is_free)
    {
        $this->is_free = $is_free;
    }


}

src/BlogBundle/Entity/User.php
<?php
namespace BlogBundle\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Serializable;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Validator\Constraints as Assert;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\VarDumper\VarDumper;

/**
 * @ORM\Entity(repositoryClass="BlogBundle\Entity\Repository\UserRepository")
 * @ORM\Table(name="public.user")
 * @UniqueEntity(fields="email", message="Sorry, this email address is already in use.")
 * @UniqueEntity(fields="username", message="Sorry, this username is already taken.")
 */
class User implements UserInterface, Serializable
{


    /**
     * Конструктор класса User
     */
    public function __construct()
    {
        $this->posts = new  ArrayCollection();
        $this->inTransactions = new ArrayCollection();
        $this->outTransactions = new ArrayCollection();
        $this->likes = new ArrayCollection();
        $this->userRoles = new ArrayCollection();
        $this->userAssignPosts = new ArrayCollection();
        $this->created_at = new \DateTime();
        $this->balance = 0;
    }


    /**
     * @ORM\Id
     * @ORM\Column(type="integer")
     * @ORM\GeneratedValue(strategy="SEQUENCE")
     */
    protected $id;

    /**
     * @ORM\Column(type="string",unique=true,nullable=false)
     * @Assert\NotBlank()
     */
    protected $username;

    /**
     * @ORM\Column(type="string",unique=true,nullable=false)
     * @Assert\NotBlank()
     */
    protected $avatar_path;

    /**
     * @ORM\Column(type="string",nullable=false)
     */
    protected $password;


    /**
     * @ORM\ManyToMany(targetEntity="Role")
     * @ORM\JoinTable(name="user_role",
     *     joinColumns={@ORM\JoinColumn(name="user_id", referencedColumnName="id")},
     *     inverseJoinColumns={@ORM\JoinColumn(name="role_id", referencedColumnName="id")}
     * )
     *
     * @var ArrayCollection $userRoles
     */
    protected $userRoles;


    /**
     * @ORM\ManyToMany(targetEntity="Post")
     * @ORM\JoinTable(name="user_post",
     *     joinColumns={@ORM\JoinColumn(name="user_id", referencedColumnName="id")},
     *     inverseJoinColumns={@ORM\JoinColumn(name="post_id", referencedColumnName="id")}
     * )
     *
     * @var ArrayCollection $userAssignPosts
     */
    protected $userAssignPosts;

    /**
     * @ORM\Column(type="string", unique=true, nullable=false)
     * @Assert\NotBlank()
     * @Assert\Email()
     */
    protected $email;


    /**
     * @ORM\Column(type="datetime")
     */
    protected $created_at;

    /**
     * @ORM\Column(type="float")
     */
    protected $balance;

    /**
     *
     * @Assert\NotBlank()
     * @Assert\Length(max=4096)
     */
    protected $password_repeat;

    /**
     * @return mixed
     */
    public function getUserAssignPosts()
    {
        return $this->userAssignPosts;
    }

    /**
     * @param mixed $userAssignPosts
     */
    public function setUserAssignPosts($userAssignPosts)
    {
        $this->userAssignPosts = $userAssignPosts;
    }


    /**
     * @return mixed
     */
    public function getAvatarPath()
    {
        return $this->avatar_path;
    }

    /**
     * @param mixed $avatar_path
     */
    public function setAvatarPath($avatar_path)
    {
        $this->avatar_path = $avatar_path;
    }


    /**
     * @return mixed
     */
    public function getPasswordRepeat()
    {
        return $this->password_repeat;
    }

    /**
     * @param mixed $password_repeat
     */
    public function setPasswordRepeat($password_repeat)
    {
        $this->password_repeat = $password_repeat;
    }

    /**
     * Get id
     *
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set username
     *
     * @param string $username
     *
     * @return User
     */
    public function setUsername($username)
    {
        $this->username = $username;

        return $this;
    }

    /**
     * Get username
     *
     * @return string
     */
    public function getUsername()
    {
        return $this->username;
    }

    /**
     * Set password
     *
     * @param string $password
     *
     * @return User
     */
    public function setPassword($password)
    {
        $this->password = $password;

        return $this;
    }

    /**
     * Get password
     *
     * @return string
     */
    public function getPassword()
    {
        return $this->password;
    }

    /**
     * Set email
     *
     * @param string $email
     *
     * @return User
     */
    public function setEmail($email)
    {
        $this->email = $email;

        return $this;
    }

    /**
     * Get email
     *
     * @return string
     */
    public function getEmail()
    {
        return $this->email;
    }


    /**
     * Set createdAt
     *
     * @param \DateTime $createdAt
     *
     * @return User
     */
    public function setCreatedAt($createdAt)
    {
        $this->created_at = $createdAt;

        return $this;
    }

    /**
     * @return mixed
     */
    public function getPosts()
    {
        return $this->posts;
    }

    /**
     * @param mixed $posts
     */
    public function setPosts($posts)
    {
        $this->posts = $posts;
    }

    /**
     * @return mixed
     */
    public function getLikes()
    {
        return $this->likes;
    }

    /**
     * @param mixed $likes
     */
    public function setLikes($likes)
    {
        $this->likes = $likes;
    }

    /**
     * @ORM\OneToMany(targetEntity="Post", mappedBy="user")
     */
    protected $posts;

    /**
     * @ORM\OneToMany(targetEntity="Transaction", mappedBy="targetUser")
     */
    protected $inTransactions;


    /**
     * @ORM\OneToMany(targetEntity="Transaction", mappedBy="sourceUser")
     */
    protected $outTransactions;

    /**
     * @ORM\OneToMany(targetEntity="Like", mappedBy="user")
     */
    protected $likes;

    /**
     * Get createdAt
     *
     * @return \DateTime
     */
    public function getCreatedAt()
    {
        return $this->created_at;
    }

    /**
     * Returns the roles granted to the user.
     *
     * <code>
     * public function getRoles()
     * {
     *     return array('ROLE_USER');
     * }
     * </code>
     *
     * Alternatively, the roles might be stored on a ``roles`` property,
     * and populated in any number of different ways when the user object
     * is created.
     *
     * @return (Role|string)[] The user roles
     */
    public function getRoles()
    {
        return $this->getUserRoles()->toArray();
    }

    public function setRole($role)
    {
        $this->userRoles[] = $role;
    }

    /**
     * @return mixed
     */
    public function getInTransactions()
    {
        return $this->inTransactions;
    }

    /**
     * @param mixed $inTransactions
     */
    public function setInTransactions($inTransactions)
    {
        $this->inTransactions = $inTransactions;
    }

    /**
     * @return mixed
     */
    public function getOutTransactions()
    {
        return $this->outTransactions;
    }

    /**
     * @param mixed $outTransactions
     */
    public function setOutTransactions($outTransactions)
    {
        $this->outTransactions = $outTransactions;
    }


    /**
     * Returns the salt that was originally used to encode the password.
     *
     * This can return null if the password was not encoded using a salt.
     *
     * @return string|null The salt
     */
    public function getSalt()
    {
        return null;
    }

    /**
     * Removes sensitive data from the user.
     *
     * This is important if, at any given point, sensitive information like
     * the plain-text password is stored on this object.
     */
    public function eraseCredentials()
    {
        $this->password = "";
    }

    /**
     * Геттер для ролей пользователя.
     *
     * @return ArrayCollection A Doctrine ArrayCollection
     */
    public function getUserRoles()
    {
        return $this->userRoles;
    }

    /**
     * @return mixed
     */
    public function getBalance()
    {
        return $this->balance;
    }

    /**
     * @param mixed $balance
     */
    public function setBalance($balance)
    {
        $this->balance = $balance;
    }


    /**
     * String representation of object
     * @link http://php.net/manual/en/serializable.serialize.php
     * @return string the string representation of the object or null
     * @since 5.1.0
     */
    public function serialize()
    {
        return serialize(array(
            $this->id,
            $this->email,
            $this->password,
        ));
    }

    /**
     * Constructs the object
     * @link http://php.net/manual/en/serializable.unserialize.php
     * @param string $serialized <p>
     * The string representation of the object.
     * </p>
     * @return void
     * @since 5.1.0
     */
    public function unserialize($serialized)
    {
        list (
            $this->id,
            $this->email,
            $this->password,
            ) = unserialize($serialized);
    }

    /**
     * @return bool
     */
    public function saveAvatar()
    {
        $web_dir = '/uploads/avatars/' . self::randStrGen(10);
        $server_new_path = '/var/www/study_symfony/web' . $web_dir;

        if (move_uploaded_file($this->getAvatarPath()->getRealPath(), $server_new_path)) {
            $this->avatar_path = $web_dir;
            return true;
        };
        return false;
    }

    /**
     * @param $len
     * @return string
     */
    static function randStrGen($len)
    {
        $result = "";
        $chars = "abcdefghijklmnopqrstuvwxyz0123456789";
        $charArray = str_split($chars);
        for ($i = 0; $i < $len; $i++) {
            $randItem = array_rand($charArray);

src/BlogBundle/Form/PostForm.php
<?php
/**
 * Created by PhpStorm.
 * User: rail
 * Date: 30.11.16
 * Time: 21:42
 */

namespace BlogBundle\Form;


use Ivory\CKEditorBundle\Form\Type\CKEditorType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\CheckboxType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Validator\Constraints\Length;
use Symfony\Component\Validator\Constraints\NotBlank;
use Symfony\Component\Validator\Mapping\ClassMetadata;

class PostForm extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder->add('is_free', CheckboxType::class, array('label' => "Бесплатная запись","required"=>false));
        $builder->add('title', TextType::class,array('label' => "Тема"));
        $builder->add('body', CKEditorType::class, array('label' => false));
    }


    public static function loadValidatorMetadata(ClassMetadata $metadata)
    {
        $metadata->addPropertyConstraints('title', [new Length([
            'max' => 255]), new NotBlank()]);
        $metadata->addPropertyConstraints('body', [new Length([
            'max' => 255]), new NotBlank()]);
    }

    public function configureOptions(OptionsResolver $resolver)
    {

    }

    public function getBlockPrefix()
    {
        return 'post';
    }
}

src/BlogBundle/Resources/views/Post/create.html.twig
{# src/Blogger/BlogBundle/Resources/views/Comment/form.html.twig #}

{{ form_start(form, { 'action': path('post_add') , 'method': 'POST', 'attr': {'class': 'blogger'} }) }}

 {{ form_errors(form) }}

            {{ form_row(form.title,{'attr':{'class':'form-control'}}) }}
            {{ form_row(form.is_free,{'attr':{'class':'form'}}) }}
            {{ form_row(form.body,{'attr':{'class':'form-control'}}) }}

            {{ form_rest(form) }}

<p>
    <input type="submit" value="Опубликовать">
</p>
{{ form_end(form) }}

src/BlogBundle/Resources/views/Post/post.html.twig
{% extends 'BlogBundle::layout.html.twig' %}
{% block body %}

    <div class="panel panel-default">
        <div class="panel-heading">
            <div class="row">
                <div class="col-xs-3">

                    <img src="{{ post.User.avatarPath }}" alt="not avatar" width="100" height="100">
                </div>
                <div class="col-xs-9">
                    <h3>
                        <p>{{ post.User.username }} опубликовал
                            <time datetime="{{ post.createdAt|date('c') }}">{{ post.createdAt|date('l, F j, Y') }}</time>
                        </p>
                    </h3>
                </div>
            </div>
        </div>
        <div class="panel-body">
            {% if app.session.has('notice') %}
                <div class="alert alert-danger">
                    {{ app.session.flash('notice') }}
                </div>
            {% endif %}
            <div class="alert alert-warning">{{ post.title }}</div>
            {% if assign %}
                {{ post.body|raw }}
            {% else %}
                Пост доступен на платной основе <a class="btn btn-default" href="{{ path('buy_post', {'post_id':post.id}) }}">Купить</a>
            {% endif %}

            <div class="btn-group">
                {% set class ='btn-default' %}
                {% for post_like in post.likes %}
                    {% for my_like in likes %}
                        {% if (post_like.id == my_like.id ) %}
                            {% set class ='btn-primary' %}
                        {% else %}
                        {% endif %}
                    {% endfor %}
                {% endfor %}
                <div class="btn btn-default count">{{ post.likes | length }}</div>
                <div class="btn {{ class }} like" data-post_id='{{ post.id }}'>Нравиться
                    <span class="glyphicon glyphicon-heart"></span></div>
            </div>
        </div>
    </div>

{% endblock %}

src/BlogBundle/Resources/views/Post/posts.html.twig
{# src/Blogger/BlogBundle/Resources/views/Page/index.html.twig #}
{% extends 'BlogBundle::layout.html.twig' %}

{% block body %}
    {% for post in posts %}
        <div class="panel panel-default">
            <div class="panel-heading">
                <div class="row">
                    <div class="col-xs-3">

                        <img src="{{ post.User.avatarPath }}" alt="not avatar" width="100" height="100">
                    </div>
                    <div class="col-xs-9">
                        <h3><p>{{ post.User.username }} опубликовал
                                <time datetime="{{ post.createdAt|date('c') }}">{{ post.createdAt|date('l, F j, Y') }}</time>
                            </p></h3>
                    </div>
                </div>
            </div>
            <div class="panel-body">

                <div class="alert alert-warning">{{ post.title }}</div>
                {{ post.body|raw }}
                <div class="btn-group">
                    {% set class ='btn-default' %}
                    {% for post_like in post.likes %}
                        {% for my_like in likes %}
                            {% if (post_like.id == my_like.id ) %}
                                {% set class ='btn-primary' %}
                            {% else %}
                            {% endif %}
                        {% endfor %}
                    {% endfor %}
                    <div class="btn btn-default count">{{ post.likes | length }}</div>
                    <div class="btn {{ class }} like" data-post_id='{{ post.id }}'>Нравиться
                        <span class="glyphicon glyphicon-heart"></span></div>
                </div>
            </div>
        </div>
    {% else %}
        <p>Постов нет</p>
    {% endfor %}

{% endblock %}

src/BlogBundle/Resources/views/Post/posts_list.html.twig
{# src/Blogger/BlogBundle/Resources/views/Page/index.html.twig #}
{% extends 'BlogBundle::layout.html.twig' %}

{% block body %}
    <ul class="list-group">

    {% for post in posts %}
        <li class="list-group-item"><a href="{{ path('post', { 'post_id': post.id }) }}">{{ post.title }}
    </a>
        {% if post.isFree == false %}
        <b style="color: red">Этот пост является платным</b>
        {% endif %}

            </li>
        {% else %}
            <p>Постов нет</p>
            {% endfor %}
            </ul>

            {% endblock %}